import {
  AlertCircle,
  BadgeCheck,
  BarChart3,
  Bell,
  BotMessageSquare,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  ChartNoAxesColumnIncreasing,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleGauge,
  CircleUserRound,
  Crown,
  ExternalLink,
  FileText,
  FileUp,
  FileUser,
  House,
  Info,
  Lock,
  LogOut,
  Mail,
  MessageSquareText,
  MessagesSquare,
  Pencil,
  Play,
  RefreshCw,
  RotateCcw,
  Send,
  Settings,
  Share2,
  Star,
  Target,
  Timer,
  Unlock,
  User,
  X
} from "lucide-react-native";

import { COLORS, ICON_SIZES } from "../../theme";

const ICONS = {
  back: ChevronLeft,
  badge: BadgeCheck,
  calendar: CalendarDays,
  chart: ChartNoAxesColumnIncreasing,
  check: Check,
  close: X,
  company: BriefcaseBusiness,
  document: FileText,
  down: ChevronDown,
  edit: Pencil,
  error: CircleAlert,
  external: ExternalLink,
  gauge: CircleGauge,
  home: House,
  info: Info,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  message: MessageSquareText,
  next: ChevronRight,
  notification: Bell,
  play: Play,
  practice: MessagesSquare,
  premium: Crown,
  profile: CircleUserRound,
  progress: BarChart3,
  refresh: RefreshCw,
  resume: FileUser,
  retry: RotateCcw,
  send: Send,
  settings: Settings,
  share: Share2,
  sparkles: BotMessageSquare,
  star: Star,
  success: CircleCheck,
  target: Target,
  technical: BrainCircuit,
  timer: Timer,
  unlock: Unlock,
  up: ChevronUp,
  upload: FileUp,
  user: User,
  verified: BadgeCheck,
  warning: AlertCircle
};

export default function AppIcon({
  color = COLORS.text,
  name = "info",
  size = ICON_SIZES.row,
  strokeWidth = 2.3,
  style
}) {
  const Icon = ICONS[name] || Info;

  return <Icon color={color} size={size} strokeWidth={strokeWidth} style={style} />;
}
